color: null
fieldLayouts:
  1e5b6071-d38a-429e-b593-85178b4ce616:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-10T20:44:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5944e5f4-f7b7-4a76-9d07-a7f580e0869e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T20:46:33+00:00'
            elementCondition: null
            fieldUid: aee3f8fe-3f38-4224-8791-e0c8b3d7b017 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef491722-94d2-41e4-8248-29bffc863888
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T20:46:33+00:00'
            elementCondition: null
            fieldUid: 64e215c1-22c4-4d3d-adc3-9f8f2536d852 # Short Description
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f04e3142-2c98-49cb-aa13-cbf7c6531e79
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-10T23:07:12+00:00'
            elementCondition: null
            fieldUid: 42e1856a-3438-4d4c-b094-2eddd66904c1 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0777d9f4-6f2b-4aae-abbd-d400345e7727
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ddea95bd-3b08-479e-a77c-a433dd84cf2a
        userCondition: null
handle: card
hasTitleField: true
icon: square
name: Card
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
