color: null
fieldLayouts:
  a30b9539-9d8d-4826-91c5-acbd029bc1dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T18:33:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 831c76b7-4374-4e0d-9f45-3ebdc39e5344
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T18:34:51+00:00'
            elementCondition: null
            fieldUid: aee3f8fe-3f38-4224-8791-e0c8b3d7b017 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 040f6fae-1190-4826-b63c-bd2f6928ae06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T18:34:51+00:00'
            elementCondition: null
            fieldUid: 3e12bea0-34ff-4c7f-9339-e4857d97b9ae # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51a9ab7e-a37b-46fd-a013-f44b79654ea2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c48241cb-e623-4c6a-9eaf-cc7ac6c49e8a
        userCondition: null
handle: imageBanner
hasTitleField: false
icon: image
name: 'Image Banner'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
