color: null
fieldLayouts:
  32c5a58a-090c-4369-bd91-88c7d7a48b8a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-17T18:32:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cbb32768-5642-4a1f-a38a-84303ed565b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T18:34:00+00:00'
            elementCondition: null
            fieldUid: 3e12bea0-34ff-4c7f-9339-e4857d97b9ae # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d32b5cce-b572-451a-aa89-cfab7f091dd8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-17T18:34:00+00:00'
            elementCondition: null
            fieldUid: 64e215c1-22c4-4d3d-adc3-9f8f2536d852 # Short Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a12916e2-9cb5-4209-92d2-045751036987
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58b6c499-5cd0-411d-b826-e91348d08f52
        userCondition: null
handle: textBanner
hasTitleField: false
icon: text
name: 'Text Banner'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
