baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Craft Component Library Demo'
primary: true
siteGroup: fa8a0560-9f5d-45dd-ac35-76f749e96a7c # Craft Component Library Demo
sortOrder: 1
