columnSuffix: null
handle: cardLink
instructions: null
name: Link
searchable: false
settings:
  maxLength: 255
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              - '*'
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
