fieldLayouts:
  bc1d5a96-c3ee-4186-a365-eccb1b5b19ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-16T21:12:55+00:00'
            elementCondition: null
            fieldUid: ce7c73fe-2959-4535-9336-247f701cdda3 # Navigation Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c98cff44-257b-461e-bfab-f0df99859ca6
            userCondition: null
            warning: null
            width: 100
        name: Navigation
        uid: fe8c1777-9cbf-42ef-95a1-8cdba1601796
        userCondition: null
handle: masthead
name: Masthead
sortOrder: 1
