defaultPlacement: end
enableVersioning: true
entryTypes:
  - 252949bb-1915-4a96-a783-d88b904da52d # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  705231e4-6a10-4c03-80f4-69c51c381304: # Craft Component Library Demo
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
